### ISSUE TITLE
Is this Swift 2.3 or 3.0?

### ISSUE THREAD

**Issue by dfreniche** [Webtrekk/webtrekk-ios-sdk#1]
Hi, 

Trying to add your library to an old project, Xcode8 complains about legacy Swift code (2.3) that needs to be converted:

```
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
```

I've looked in your branches / tags / README but can't find which combination of Xcode / Swift is required in order to use this library.

Can you please help me?

As a workaround I'll try with Xcode 7

Thanks!

**Comment by arsen-vartbaronov** [comment]
Hi, Diego

The code that is in github right now can be used for Xcode 7 and Swift 2.2 only. However we are working on moving to Swift 3 And I expected this will happened in this or next week. If for you is important to do in in Swift 2.3 only you can provide me this information with information what company you are represented. I will forward this request to our management team.

**Comment by dfreniche** [comment]
Hi Arsen,

Thanks for getting back to me so quickly

- So if I've understood it right this week you'll push a Swift 2.3 update. Any chances of Swift 3.0 for use with Xcode 8? :-D
- also, it would be useful to update the README to avoid confusion with supported Xcode / Swift version

Thanks!

**Comment by arsen-vartbaronov** [comment]
Hi, Diego.

This week I do Swift 3.0. 
Swift 2.3 it is something we are not going to support so far.

I will update README with Swift 3.0 update.

**Comment by arsen-vartbaronov** [comment]
Version 4.1.0 with Swift 3.0 and Xcode8 support is added to Cocoapods. If you need additional support for version Swift 2.3 please let me know and report separate issue. Also readme was updated in section Requirements for Xcode and Swift version support.
