### ISSUE TITLE
How to initialize tracking in Objective C project

### ISSUE THREAD

**Issue by kumarpatel** [Webtrekk/webtrekk-ios-sdk#16]
I've installed WebTrekk iOS sdk via cocoapods
My Podfile has
```
use_frameworks!
  pod 'Webtrekk'
```

Imported this in my AppDelegate.m (This auto-completed for me. So it's most likely right. ¯\_(ツ)_/¯)
Used the following doc to ensure the import statement is correct:
https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html
```
#import <Webtrekk/Webtrekk-Swift.h>
```
I'm using WebTrekk usage doc from https://support.webtrekk.com/hc/en-us/articles/115001526005-iOS-Tracking-v4

Swift code to init tracker is `try! WebtrekkTracking.initTrack()`

I'm unable to call `initTrack` function in Objective C
`[WebtrekkTracking initTrack]`

Thoughts?

**Comment by MBing** [comment]
We don't support Objective-C. So I will close this ticket.
