### ISSUE TITLE
Change configuration after tracker has been initialized throws an error

### ISSUE THREAD

**Issue by pfrischmuth** [Webtrekk/webtrekk-ios-sdk#19]
When I try to (re)start the tracker with another configuration file after it has been already initialized, I receive the following error:

`[Webtrekk] [ERROR] Webtrekk SDK has been already initialized.`

There seems to be no way currently to reset the tracker instance, since it is an internal var. In the example code Webtrekk is imported with`@testable` and thus the tracker var can be accessed, but this is no option for release code.

Is there a way to work around this issue or are there plans to fix this in the near future?

We are currently still using a 3.x version of the SDK, which allows us to change configuration parameters after initialization. We need to update to a 4.x version however in order to use the user properties feature.

**Comment by arsen-vartbaronov** [comment]
Dear @pfrischmuth can you explain why you need to change configuration after it has been initialized? What is final goal you would like to achieve? 
It would be good if you can provide both configurations and I can look at difference.

**Comment by pfrischmuth** [comment]
We need to change the `trackId` as well as the `trackDomain`.

We use different tracking IDs and domains for different countries. The country can be selected within the app and without quitting the app.

**Comment by olebahlmann** [comment]
Hi @pfrischmuth,
your desired outcome can be solved in a simpler manner using Webtrekk data profiles which can be configured in your account. Feel free to contact me directly to learn more about this.
