### ISSUE TITLE
Doesn't work under Xcode 8

### ISSUE THREAD

**Issue by whorbach** [Webtrekk/webtrekk-ios-sdk#2]
Error: Converting to Swift 2.3 not possible.

**Comment by arsen-vartbaronov** [comment]
Hi, Whorbach

Please see this conversation: https://github.com/Webtrekk/webtrekk-ios-sdk/issues/1#issuecomment-252579972

**Comment by arsen-vartbaronov** [comment]
Version 4.1.0 with Swift 3.0 and Xcode8 support is added to Cocoapods
