### ISSUE TITLE
Xcode 9 support – CryptoSwift dependency too strict

### ISSUE THREAD

**Issue by Dschee** [Webtrekk/webtrekk-ios-sdk#21]
Xcode 9 GM seed was released yesterday. Developers are expected to use Xcode 9 from now on, but the CryptoSwift version is defined way too strict in the Cartfile. It should better be `~> 0.7` instead of the very restrictive `== 0.6.9` which is not a good idea, especially for a framework.

**Comment by arsen-vartbaronov** [comment]
Dependency from CryptoSwift has been removed
