### ISSUE TITLE
Xcode 9 support – fix build errors

### ISSUE THREAD

**Issue by Dschee** [Webtrekk/webtrekk-ios-sdk#23]
The project as it currently is doesn't build with Xcode 9 GM seed.

**Comment by arsen-vartbaronov** [comment]
@Dschee 
Currently it compiled as Swift 3.2. This week will be released version with Swift4 and released Xcode9 support.

**Comment by arsen-vartbaronov** [comment]
Swift4 version is released to Cocoapods with version 4.8.1. Sorry for delay.
