### ISSUE TITLE
How to set custom parameters / variables / "Schlagwort"

### ISSUE THREAD

**Issue by mobru** [Webtrekk/webtrekk-ios-sdk#37]
Hi,

I seem to have problems with adding custom parameters to a tracking call. I'm using version 4.10.0 with a Swift 4 project, my deployment target is iOS 10. I do not use autotracking or tag integration, everything is being tracked manually.
Everything else works just fine, I can, for example, set a content group which will also be sent.

Here's the initialization:
```swift
public static func initTracking() {
    guard let configurationFile = Bundle.main.url(forResource: "webtrekk_config",
                                                  withExtension: "xml") else {
        fatalError("Cannot locate webtrekk_config.xml")
    }
    try! WebtrekkTracking.initTrack(configurationFile)
}
```
and here's the code for the actual tracking:
```swift
public static func trackPageImpression(_ webtrekkData: WebtrekkData) {
    guard let contentId = webtrekkData.contentId, 
          let contentGroup = webtrekkData.contentGroup, 
          var customParameter = webtrekkData.customParameter else {
        return
    }
    
    customParameter["cs1"] = Helper.isLoggedIn() ? "1" : "0"
    
    DispatchQueue.main.async {
        let tracker = WebtrekkTracking.instance().trackerForPage(contentId)
        
        for parameter in customParameter {
            tracker[parameter.key] = parameter.value
        }
        
        tracker.pageProperties.groups = contentGroup
        tracker.variables = customParameter
        tracker.trackPageView()
    }
}
```
An example for an entry in the `contentGroup` looks like this: `TrackingValue = 1, value = "someString"`, and the `customParameter` is a `[String : String]` dictionary with example values of: `"1" : "anotherString", "2" : "yetAnotherString", "cs1" : "0", ...`.

For reference, my `WebtrekkData` object looks like this:
```swift
public struct WebtrekkData {
    var contentId: String?
    var contentGroup: [Int : TrackingValue]?
    var customParameter: [String : String]?
    var launchLiveaccount: String?
}
```

Again, everything but the custom parameters work just fine, even though I tried assigning them to the `tracker` as a dictionary (`tracker[parameter.key] = parameter.value`) **and** assigning them to the `tracker`'s `variables` property (`tracker.variables = customParameter`). They appear as "null" in the dashboard under "**Schlagwort**" (dashboard is in German).

Any help would be greatly appreciated!

**Comment by olebahlmann** [comment]
Hi @mobru, thanks for reaching out. Could you let me know (by email or pn) which account this is? I believe the problem might be in the setup.

**Comment by mobru** [comment]
Hi @olebahlmann! Thanks for the quick reply. I sent you an email (I already have your address from a previous conversation, please let me know if you didn't get the mail)!

**Comment by MBing** [comment]
Hi @mobru 
Can you log the data you get here in the for-loop:
```
       for parameter in customParameter {
            tracker[parameter.key] = parameter.value
        }
```
and also the `tracker` object:
```
   let tracker = WebtrekkTracking.instance().trackerForPage(contentId)
```

Thanks!

**Comment by mobru** [comment]
Hi @MBing!

This might be a dumb question, but - how exactly do you want me to log it?

**Comment by MBing** [comment]
@mobru 
Did you write any tests? Then it would also be easier to check that we actually get something back. My first impression is that the for loop looks good. But I am not sure about the tracker object you get back, which methods/keys you can use with them. There used to be some tests where we used `tracker.variables["test"] = "test"` but these were commented out and I would need to have a look into the docs why that is still in there. 

You could use:
https://github.com/Webtrekk/iOS-SDK-Example-App

This should be an example application with some mocks doing some tests. But unfortunately I don't have a test in there for your specific case with the usage of `trackerForPage`. So I need to look into it. Otherwise you could just print the output of a request (Debug). In the example app there are some examples on how we log the data. In order to retrieve if the request is working and what is being received by the request. 

Hope this helps and yeah I will look into it.

**Comment by MBing** [comment]
Hi @mobru 

So below I have an example that should work better. A few notes:

  1. To check if the user is logged in we need to add this to the `tracker.sessionDetails` and we will create the `cs1` for Customer Session 1 and `cs2` for Customer Session 2 etc..
  2. To set custom Page Parameters in your case, you need to add it to the `tracker.pageProperties.details` dictionary which uses an `[Int: String]` structure. So below make sure the structure is the same. This way you could also skip the `for-loop` of course.
  3. The identifier of your page should be set in the end after all the tracker params are set and you only need to create an instance in the beginning. Then you can just add the unique id to your `trackPageView` method which expects a `String`.
  4. If for any case the `tracker.pageProperties.details` do not seem what you need (which is possible of course), then yes use `tracker.variables = customParameters` and you can keep the structure of your current dict `[String: String]`. 
```swift
// so either [Int: String]
tracker.variables = customParameters
// OR [String: String]
tracker.pageProperties.details = customParameters 
// I added the 's' as there will be more than 1 
// and then you should be able to skip the for-loop
```

Full example and make sure to change the `customParameter` Dictionary to a `[Int: String]` structure if you want to use the `pageProperties.details`. And of course make the variable plural would also be advised for clarity. 
```swift
public static func trackPageImpression(_ webtrekkData: WebtrekkData) {
    guard let contentId = webtrekkData.contentId, 
          let contentGroup = webtrekkData.contentGroup, 
          var customParameters = webtrekkData.customParameters else {
        return
    }
    
    DispatchQueue.main.async {
        let tracker = WebtrekkTracking.instance()        
        tracker.sessionDetails[1] = Helper.isLoggedIn() ? "1" : "0"
        tracker.pageProperties.groups = contentGroup
        tracker.pageProperties.details = customParameters
        tracker.trackPageView(contentId)
    }
}
```

Hope this helps and let me know if you have further questions/problems.

**Comment by mobru** [comment]
Hi again @MBing!

Thank you very much for the example and your suggestions!
Unfortunately, instantiating the tracker with `WebtrekkTracking.instance()` creates a `Tracker` object, whereas `WebtrekkTracking.instance().trackerForPage(contentId)` creates a `PageTracker`. And the `Tracker` object lacks the `sessionDetails`, `pageProperties`, and `variables` properties.

Trying to cast to `Tracker` to a `PageTracker` -
```swift
guard let tracker = WebtrekkTracking.instance() as? PageTracker else { return }
```
does not work either. And even if it would, I couldn't call `trackPageView()` with my `contentId` String as a Parameter.

What I _could_ do, is instantiating the tracker as before, and assigning my custom parameters to `pageProperties.details` (see code below) - but you said the the tracker should not be instantiated like this in my case?
```swift
public static func trackPageImpression(_ webtrekkData: WebtrekkData) {
    guard let contentId = webtrekkData.contentId,
          let contentGroup = webtrekkData.contentGroup,
          let customParameters = webtrekkData.customParameters else {
        return
    }
    
    DispatchQueue.main.async {
        // call trackerForPage() to get a PageTracker object
        let tracker = WebtrekkTracking.instance().trackerForPage(contentId)
        
        tracker.sessionDetails[1] = Helper.isLoggedIn() ? "1" : "0"
        tracker.pageProperties.groups = contentGroup
        tracker.pageProperties.details = customParameters

        // no parameter
        tracker.trackPageView()
    }
}
```

**Comment by MBing** [comment]
That is actually ok, it was more that I couldn't find an example on the usage of `trackerForPage` so I wasn't sure on how it will work. But your implementation, given the fact that you get a `PageTracker` back should also work. The `trackPageView` argument is optional. 

So your last implementation works?

**Comment by mobru** [comment]
It looks like it!

After adding the WebTrekk debug logs
```swift
WebtrekkTracking.defaultLogger.minimumLevel = .debug
WebtrekkTracking.defaultLogger.testMode = true
```
and looking at the console output, everything seems to be sent!

I need to re-check with the people in charge of tracking / marketing for this project if everything arrives as well, but it looks like using `tracker.pageProperties.details` instead of `tracker.variables` (the for `tracker[parameter.key] = parameter.value` loop) for the custom parameters did the trick!

Assuming that everything _does_ arrive (which it should) - thank you very much for your help @MBing and @olebahlmann!

**Comment by MBing** [comment]
Great! Then I will close this issue.

**Comment by pradeepktg** [comment]
> ```swift
> let tracker = WebtrekkTracking.instance().trackerForPage(contentId)
> ```

Hi @mobru - I have the requirements to create a content group, action parameter, site parameter, custom parameter, and formulare. Could you please share me how did you create a content group and how did you call "trackPageImpression" method? and what is "TrackingValue"?

**Comment by mobru** [comment]
Hi @pradeepktg !

The `trackPageImpression()` method is just a custom method I wrote myself. Each appropriate class calls it when it's time to track a page impression (e.g. in `viewDidAppear` and when the tracking data is set).

> how did you create a content group

As I wrote above, the custom `WebtrekkData` struct I used looks like this:
```swift
public struct WebtrekkData {
    var contentId: String?
    var contentGroup: [Int : TrackingValue]?
    var customParameter: [String : String]?
    var launchLiveaccount: String?
}
```
So a content group is a dictionary with an integer key and a string (or rather: a `TrackingValue`) as its value. For example:
```swift
[1 : "foo", 2 : "bar"]
```
The `TrackingValue` comes from Webtrekk itself, see the class `TrackingValue.swift` in the Webtrekk lib. You can initialise one like this:
```swift
TrackingValue(stringLiteral: "foo")
```

I hope this helps - good luck with implementing all your requirements!

**Comment by pradeepktg** [comment]
Thanks, @mobru. Yes, I understand `trackPageImpression()` is a custom method. Below is my implementation, hope it will work.

```
public struct WebtrekkData {
    var contentId: String?
    var contentGroup: [Int : TrackingValue]?
    var customParameter: [Int : TrackingValue]? // I changed from [String : String], because I was getting the folowing error - Cannot assign value of type '[Int : String]' to type '[Int : TrackingValue]?'
    var launchLiveaccount: String?   
}

func trackPageImpression(_ webtrekkData: WebtrekkData) {
        guard let contentId = webtrekkData.contentId,
            let contentGroup = webtrekkData.contentGroup,
            let customParameters = webtrekkData.customParameter else {
                return
        }

        DispatchQueue.main.async {
           let tracker = WebtrekkTracking.instance().trackerForPage(contentId)
//            for parameter in customParameters {
//                tracker[parameter.key] = parameter.value
            //            }
            tracker.pageProperties.groups = contentGroup
            tracker.pageProperties.details = customParameters
        }
    }

override func viewWillAppear() {
       let params = [1: TrackingValue.constant("Sample content Group 1")]
        let group = [1: TrackingValue.constant("Contentgroup 1")]
        let data = WebtrekkData.init(contentId: "Quickstart_iOS", contentGroup: group, customParameter: params, launchLiveaccount: nil)
        trackPageImpression(data)
}
```

By the way, do you know how to send feedback? somewhere I read, we can send a max of 255 Characters. I have custom form and it has custom formfield. I just need to send the form name, form field name and value. It would be great if you can share your knowledge if you had done this before

**Comment by mobru** [comment]
Hi again!

I guess this should work. But don't forget to call `tracker.trackPageView()` after settings its properties (it's missing in your snippet at the moment).
As for feedback - I unfortunately have no idea. Best check the documentation or open an issue if you can't find anything on it there. 

Oh and also: you should probably call `trackPageImpression()` in `viewDidAppear`, not in `viewWillAppear`. Otherwise it might get called too often (on an incomplete edge-swipe for example). But I guess that depends on what exactly you want to track.

**Comment by pradeepktg** [comment]
Oh yes, I was cleaning the code and missed the `tracker.trackPageView()`while sending to you. Ok, now i'm calling the function in viewDidAppear. I'll update you if it works. Thanks again.

**Comment by pradeepktg** [comment]
@mobru It works. Thanks! Now I left with sending the Feedback.
