### ISSUE TITLE
Unable to use framework when build using Carthage

### ISSUE THREAD

**Issue by anefkens** [Webtrekk/webtrekk-ios-sdk#38]
Hi, 

When building the framework using Carthage the framework build cannot be used. It returns a number of compile errors inside the framework.  I'm using Xcode 9.2 to develop/build. 

I noticed that when the product is build, inside the framework in the folder "Headers" I see a folder structure appearing that resembles my folder structure of how I setup the project. I.e. "<HomeFolder>/Development/repos/<Projectname>/Carthage/Checkouts/webtrekk-ios-sdk/Sources/Supporting Files" 

Inside the folder I see the Webtrekk.h. I do not see this folder structure in other framework I use.  Am using 4.10.0 of the library.

This also occurs  when doing a direct build from the Checkout of the repo in the Derived Data folder.

How would you suggest I could fix this? 

Thanks

**Comment by MBing** [comment]
Hi @anefkens 
I will have to check this next week and get back to you. 
Is there a possibility to use Cocoapods instead?

**Comment by anefkens** [comment]
Thanks for the response, but no we cannot use CocoaPods. We are now just trying to migrate to Carthage, and this is the last dependancy remaining.  But if you could take a look much appreciated.

**Comment by MBing** [comment]
Hi,
Could you help me in making a small test case with Carthage of what you are trying to accomplish, that would help me a lot and I will get on to it then asap.

**Comment by anefkens** [comment]
Steps I took:

1. Created a SingleView Project.
2. Added Cartfile: github "Webtrekk/webtrekk-ios-sdk"
3: Executed command: "carthage update --platform iOS"

After execution I see in the generated frameworks that the Reachability.framworks, in the sub-folder "Headers" the headers for Reachability are there. The full path on my Mac is for the header file in the Reachability: /DevelopmentStore/Repos/DemoWebTrekkCarthage/Carthage/Build/iOS/Reachability.framework/Headers/Reachability.h

In the  Webtrekk.framework in the Headers Folder I see the following path: "/DevelopmentStore/Repos/DemoWebTrekkCarthage/Carthage/Build/iOS/Webtrekk.framework/Headers/DevelopmentStore/Repos/DemoWebTrekkCarthage/Carthage/Checkouts/webtrekk-ios-sdk/Sources/Supporting Files/Webtrekk.h" instead of the Webtrekk.h file.

So to me something is not right in your Build settings, since there is a difference between the two contains the header files and this is the same as it is for our other dependancies. 

I can share a zip of the complete demo project. But I assume that when you follow the same steps I took, you will get the same results, since I had the same result in our main project and the demo project as well.

**Comment by MBing** [comment]
Ok, thanks, yeah that does seem odd indeed.

**Comment by anefkens** [comment]
Hi Martin, Any news on this issue?

**Comment by MBing** [comment]
Hi Arnold,

Currently I am fixing the XCode 9.3 bug first and getting into some testing. As we don't have any yet. Tbh I haven't written a Carthage library before, so it's a bit of a challenge and the previous dev also took a first time hit while creating this. If you have any resources, that would be great!
But I plan to finish the bug somewhere today/Monday and then I will get to Carthage.

**Comment by anefkens** [comment]
I briefly went in the Webtrekk.xcodeproj, and found the following build setting that is different from other dependancies.  In the Swift Compiler - General I found the path set for:

- "Objective-C Bridging Header" :  $(SRCROOT)/Source/Supporting Files/Webtrekk-Bridging-Header.h
- "Objective-C Generated Interface Header Name" : $(SRCROOT)/Source/Supporting Files/Webtrekk.h

In my understanding the $(SRCROOT) is being expanded and then added to the path by the compiler. And thus resulting in the second path. Also as far as I understood, you do not need to override these in the first place. Other dependancies, like the Reachability, have these also not overridden. 

I'm setting up a fork to test, however I'm already running Xcode 9.3 in our production environments.

**Comment by MBing** [comment]
Running it locally, Carthage seems to work for tvOS & watchOS, but not for iOS. Which obviously is the most important. I am running some tests
![screen shot 2018-04-16 at 08 56 37](https://user-images.githubusercontent.com/2140223/38794102-339c7310-4154-11e8-805d-e26298079aa4.png)

Is your output similar when running `carthage update` ?

Thanks!

**Comment by anefkens** [comment]
Same error 65 when doing Carthage update.

**Comment by anefkens** [comment]
** ARCHIVE FAILED **


The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64
(2 failures)

**Comment by MBing** [comment]
Will close when release is done, was auto closed by github. ;)

**Comment by MBing** [comment]
Hi Arnold,

Can you try this in your Cartfile:
`github "Webtrekk/webtrekk-ios-sdk" "4.11"`

**Comment by anefkens** [comment]
Tried and same result. 

After execution I see in the generated frameworks that the Reachability.framworks, in the sub-folder "Headers" the headers for Reachability are there. The full path on my Mac is for the header file in the Reachability: /DevelopmentStore/Repos/DemoWebTrekkCarthage/Carthage/Build/iOS/Reachability.framework/Headers/Reachability.h

In the Webtrekk.framework in the Headers Folder I see the following path: "/DevelopmentStore/Repos/DemoWebTrekkCarthage/Carthage/Build/iOS/Webtrekk.framework/Headers/DevelopmentStore/Repos/DemoWebTrekkCarthage/Carthage/Checkouts/webtrekk-ios-sdk/Sources/Supporting Files/Webtrekk.h" instead of the Webtrekk.h file.

So no luck there.

**Comment by MBing** [comment]
I have fixed some path stuff so it's a closer file path. `Headers -> Source -> Webtrekk.h` Are you actually sure you have the framework files linked in your project?

https://koenig-media.raywenderlich.com/uploads/2017/08/navigation.gif

I tried it in a new project and I have access to the global `Webtrekk` object so I can import it without a problem and it even shows me an autocomplete of the module. I am will update 4.11 to the latest version. Can you share a print screen of the `Linked Framework and Libraries` in your project or some of the errors please?

**Comment by anefkens** [comment]
Thanks, the fix for 4.11 and the shorter path solved it for me, at least in my demo project. Linking world as the import compiles. So should work now.
