### ISSUE TITLE
[Xcode 9.3 (9E145) erorrs] Overlapping accesses

### ISSUE THREAD

**Issue by bananafish911** [Webtrekk/webtrekk-ios-sdk#39]
Hi, I have troubles with your pod after update to the latest Xcode

It gives errors like "Overlapping accesses to 'event', but modification requires exclusive access; consider copying to a local variable" when u try to modify struct using a local variable (in 10 places in total)

Here are screenshots if u haven't tested it with Xcode 9.3 yet:
https://drive.google.com/open?id=1a7JgDl3-PT2VcjvfoOxEMxnEmSwlNZNI
https://drive.google.com/open?id=1W_t2VQQ5VZUOfAGSYbSA_QPSTsVKqOEk

Here is some info about what's wrong there
https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/MemorySafety.html

**Comment by MBing** [comment]
@bananafish911 Thanks for all the info! I will look into it right away.

**Comment by bananafish911** [comment]
@MBing Thanks a lot! And yes, v4.11.0 works fine with the latest Xcode and Swift

**Comment by MBing** [comment]
Hi @bananafish911 

Can you check the latest Pod 4.11 that I just released if all still works for you as well?
There are some warnings still to be fixed, but that will be for a next release as we need to upgrade our Jenkins. Let me know if all is good. Then we can close this issue.
Thanks!
