### ISSUE TITLE
Carthage support.

### ISSUE THREAD

**Issue by thebugcode** [Webtrekk/webtrekk-ios-sdk#4]
Can we make it so that Webtrekk supports carthage? We and many other teams start using Carthage due to its lightness, it would make sense to support it

**Comment by olebahlmann** [comment]
We are looking into adding support for Carthage. But it's not at the top of the list.

**Comment by thebugcode** [comment]
I can understand that. Could you tell me how would you envision this happening? If I submitted a PR for this, maybe it could get merged

**Comment by olebahlmann** [comment]
That is exactly what we need to figure out first.

**Comment by thebugcode** [comment]
I know how, do you mind if I provide a PR, with Carthage support mostly implemented for webtrek, except a few small things where you could help so that we can ship Carthage support ?

**Comment by olebahlmann** [comment]
Please, go ahead. We'll do our best to review it quickly.

Ursu Dan <notifications@github.com> schrieb am Fr., 11. Nov. 2016, 02:37:

**Comment by arsen-vartbaronov** [comment]
@thebugcode Carthage support is done. However it would be good to validate this task. You can use already existed test project for [that](https://github.com/Webtrekk/webtrekk-ios-sdk/tree/master/CarthageTest )
