### ISSUE TITLE
How to send formfield value of 255 Characters

### ISSUE THREAD

**Issue by pradeepktg** [Webtrekk/webtrekk-ios-sdk#56]
Hi, My client had created a custom form("Formulare") and It contains "Formulare, Formularfelder, and Formularfeldwerte". How do I send data the following data - Formulare = "Feedback", Formularfelder = "textarea", Formularfeldwerte = "some string less than 255 characters". Since there is not supporting API, I tried to send data using URL encoding, I'm getting "200 Ok" status, but the data is not reflecting in Webtrekk. Could you please help in this matter?

https://clientname.webtrekk.net/xxxxxxxxxxx/fn=Feedback%7C1&ft=textarea%7CTroubleshooting helped me-lastfocusas-postman%7C0

**Comment by MBing** [comment]
Currently we don't support Forms in the SDK, only in the web (Pixel) version. And we also only support up to 255 chars, so anything larger will be cut off. 
The tracker will always return a 200 OK, unfortunately it is out of my hands to change that. But hope this info helps. :)

**Comment by pradeepktg** [comment]
@MBing Thank you.
