### ISSUE TITLE
Manual install

### ISSUE THREAD

**Issue by fotiDim** [Webtrekk/webtrekk-ios-sdk#6]
Not everyone used cocoapods. You should provide some instructions for manual install or a compiled framework ready for download.

**Comment by arsen-vartbaronov** [comment]
Hi fotiDim

Just to clarify your question. You would like to have instruction how to compiled framework. Correct?

**Comment by fotiDim** [comment]
Yes either or you can offer the compiled framework as a download.

**Comment by arsen-vartbaronov** [comment]
Hi, fotiDim

We will think about either providing framework or solid instruction, but so far you can do it using two ways:

1. You can just create some simple "Hello world" project, add cocopoads support to it and import Webtrekk pod to it. Then in Products after compilation you will see Webtrekk.framework file.
2. You can also upload whole project from github and compile ModuleTest scheme. It also produce compiled framework.

The first way is more preferably as you will get version of framework based on some library version. The second approach get you latest version. However you can also upload by tag.

Please let me now if this helps you, or you need additional information.

**Comment by arsen-vartbaronov** [comment]
You are wellcome

**Comment by arsen-vartbaronov** [comment]
I hope issue is closed.
