### ISSUE TITLE
Build fails with Xcode 12.5

### ISSUE THREAD

**Issue by ntorring** [Webtrekk/webtrekk-ios-sdk#70]
Removing the "exported: true" from the "@_specialize" tags seems to fix the issue.
A new release would be appreciated, as this is currently breaking our workflow :/

**Comment by Cordobo** [comment]
It looks like any further development is over here https://github.com/mapp-digital/MappIntelligence-iOS-v5

**Comment by stellatores** [comment]
Thank you for your comments. Indeed, we released a new version of the iOS SDK and further feature development will only be supported on the new version. However, we still maintain this version and fix any potential bugs at this point. We are aware of the issue and will update as soon as it is fixed.

**Comment by stellatores** [comment]
We released the bug fix today and it should work now Xcode 12.5. Please let us know if you have any further issues.
